### ISSUE TITLE
Spring Cloud各组件超时设置

### ISSUE THREAD

**Issue by kingschan1204** [kingschan1204/blog#7]
### Ribbon的超时
**全局设置：**

```
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
```

**局部设置：**

```
service-id:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 1000
```
其中，service-id 是Ribbon所使用的虚拟主机名，一般和Eureka Server上注册的服务名称一致，即：与**spring.application.name** 一致。

Feign的超时
从Spring Cloud Edgware开始，Feign支持使用属性配置超时：

```
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
```

> 对于老版本，可以写个feign.Request.Options ，参考：org.springframework.cloud.netflix.feign.ribbon.FeignRibbonClientAutoConfiguration#feignRequestOptions 的写法即可。

### RestTemplate的超时
一些时，我们可能使用了RestTemplate，例如
```

@Bean
@LoadBalanced
public RestTemplate restTemplate() {
  return new RestTemplate();
}
```
此时，超时可使用如下方式设置：

```
@Bean
@LoadBalanced
public RestTemplate restTemplate() {
  SimpleClientHttpRequestFactory simpleClientHttpRequestFactory = new   SimpleClientHttpRequestFactory();
  simpleClientHttpRequestFactory.setConnectTimeout(1000);
  simpleClientHttpRequestFactory.setReadTimeout(1000);
  return new RestTemplate(simpleClientHttpRequestFactory);
}
```

### Zuul的超时

Zuul的超时比较复杂，因为Zuul整合了Ribbon、Hystrix。下面分两种情况讨论：

如果Zuul的路由使用了Ribbon
那么：Zuul的超时则与Ribbon、Hystrix相关，此时Zuul的超时可以配置类似如下：

```
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 1000
```
代码解析：此种情况下，Zuul转发所使用的过滤器是org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter ，在这个过滤器中，整合了Hystrix以及Ribbon。

如果Zuul的路由未使用Ribbon
例如：Zuul的路由配置如下：

```
zuul:
  routes:
    user-route:                   # 该配置方式中，user-route只是给路由一个名称，可以任意起名。
      url: http://localhost:8000/ # 指定的url
      path: /user/**              # url对应的路径。
```
那么，此时Zuul的超时只与如下两个配置有关：

```
zuul:
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 2000
```
代码解析：直接配置URL路由的方式，用不上Ribbon，也用不上Hystrix，Zuul转发所使用的过滤器是org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter ，在这个过滤器中，Zuul使用Apache HttpClient进行转发。

在现实场景中，有时候可能两种路由方式配合使用，因此，建议大家配置以上所有属性。

### Hystrix的超时
```
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000
```
如上，Hystrix的默认超时时间是1秒。默认开启超时机制。如需关闭Hystrix的超时，可将xxx.enabled设置为false。
